version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  reviewers:
  - Dheyson
  assignees:
  - Dheyson
  labels:
  - enhancement
  ignore:
  - dependency-name: babel-preset-gatsby
    versions:
    - 0.11.0
    - 0.12.0
    - 0.12.1
    - 0.12.2
    - 1.0.0
    - 1.1.0
    - 1.2.0
    - 1.3.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.10
    - 2.32.11
    - 2.32.2
    - 2.32.3
    - 2.32.4
    - 2.32.6
    - 2.32.8
    - 2.32.9
  - dependency-name: gatsby-transformer-remark
    versions:
    - 2.15.0
    - 2.16.0
  - dependency-name: gatsby-plugin-google-analytics
    versions:
    - 2.10.0
  - dependency-name: gatsby-remark-responsive-iframe
    versions:
    - 2.10.0
  - dependency-name: react-is
    versions:
    - 17.0.1
  - dependency-name: gatsby-plugin-typography
    versions:
    - 2.11.0
